package javatex;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

public class Section extends javax.swing.JFrame {

    final private File sectiontex = new File("src\\data\\samplesection.txt");
    final private File subsectiontex = new File("src\\data\\samplesubsection.txt");
    final private File codeboxtex = new File("src\\data\\samplecodebox.txt");
    final private File pathspacetex = new File("src\\data\\samplepathspaces.txt");
    private PrintWriter output_txt, output_tex;

    private String a, b, j, l, k;
    String doc;

    public Section() {
        initComponents();
    }

    public Section(String n) throws FileNotFoundException {
        initComponents();
        this.setTitle("javatex - Add Sections");
        output_txt = new PrintWriter(new FileOutputStream("src\\output\\output_tex.txt", false));
        output_tex = new PrintWriter(new FileOutputStream("src\\output\\output_tex.tex", false));
        doc = doc + n;
        doc = doc.replaceFirst("null", "");
        updatePreview();
        Scanner sc = new Scanner(sectiontex);//section
        String p;
        while (sc.hasNext()) {
            p = sc.nextLine();
            l = l + "\n" + p;
        }

        Scanner sc1 = new Scanner(subsectiontex);//subsection
        String o;
        while (sc1.hasNext()) {
            o = sc1.nextLine();
            j = j + "\n" + o;
        }

        Scanner sc2 = new Scanner(codeboxtex);//codebox
        String q;
        while (sc2.hasNext()) {
            q = sc2.nextLine();
            b = b + "\n" + q;
        }

        Scanner sc4 = new Scanner(pathspacetex);//pathwithspaces
        String x;
        while (sc4.hasNext()) {
            x = sc4.nextLine();
            a = a + "\n" + x;
        }

    }

    void updatePreview() {
        //doc = doc.replaceAll("(?m)^[ \t]*\r?\n", "");
        preview_box.setText(doc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        title_box = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        preview_box = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        para_box = new javax.swing.JTextArea();
        para_label = new javax.swing.JLabel();
        codebox_label = new javax.swing.JLabel();
        addSec_btn = new javax.swing.JButton();
        addSubSection_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        code_box = new javax.swing.JTextArea();
        addCode_btn = new javax.swing.JButton();
        item_check = new javax.swing.JCheckBox();
        path_box = new javax.swing.JTextField();
        path_label = new javax.swing.JLabel();
        addPath_btn = new javax.swing.JButton();
        path_spaces = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        item_table = new javax.swing.JTable();
        addrow_btn = new javax.swing.JButton();
        delrow_btn = new javax.swing.JButton();
        addItems_btn = new javax.swing.JButton();
        codetoitem_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rtarrow_btn = new javax.swing.JButton();
        writetex_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        arrow_check = new javax.swing.JCheckBox();
        path_check = new javax.swing.JCheckBox();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        title_label.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        title_label.setText("Title:");

        title_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_boxActionPerformed(evt);
            }
        });

        preview_box.setColumns(20);
        preview_box.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        preview_box.setRows(10);
        preview_box.setText("\n\n\n\n\n");
        preview_box.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jScrollPane1.setViewportView(preview_box);

        para_box.setColumns(20);
        para_box.setRows(5);
        jScrollPane2.setViewportView(para_box);

        para_label.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        para_label.setText("Paragraph:");

        codebox_label.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        codebox_label.setText("Source Code Box:");

        addSec_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        addSec_btn.setText("Add Section");
        addSec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSec_btnActionPerformed(evt);
            }
        });

        addSubSection_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        addSubSection_btn.setText("Add SubSection");
        addSubSection_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubSection_btnActionPerformed(evt);
            }
        });

        code_box.setBackground(new java.awt.Color(18, 30, 49));
        code_box.setColumns(20);
        code_box.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        code_box.setForeground(new java.awt.Color(255, 255, 255));
        code_box.setRows(5);
        code_box.setText("//Write your code here");
        code_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));
        code_box.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(code_box);

        addCode_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        addCode_btn.setText("Add Source Code");
        addCode_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCode_btnActionPerformed(evt);
            }
        });

        item_check.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        item_check.setText("Enumurate Items");
        item_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_checkActionPerformed(evt);
            }
        });

        path_label.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        path_label.setText("PATH:");

        addPath_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        addPath_btn.setText("Add Path");
        addPath_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPath_btnActionPerformed(evt);
            }
        });

        path_spaces.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        path_spaces.setText("With Spaces");
        path_spaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_spacesActionPerformed(evt);
            }
        });

        item_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        item_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        item_table.setRowHeight(40);
        item_table.setSelectionBackground(new java.awt.Color(0, 102, 153));
        jScrollPane4.setViewportView(item_table);

        addrow_btn.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        addrow_btn.setForeground(new java.awt.Color(51, 153, 0));
        addrow_btn.setText("+");
        addrow_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrow_btnActionPerformed(evt);
            }
        });

        delrow_btn.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        delrow_btn.setForeground(new java.awt.Color(204, 0, 0));
        delrow_btn.setText("-");
        delrow_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delrow_btnActionPerformed(evt);
            }
        });

        addItems_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        addItems_btn.setText("Add Points/Items");
        addItems_btn.setBorder(new javax.swing.border.MatteBorder(null));
        addItems_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItems_btnActionPerformed(evt);
            }
        });

        codetoitem_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        codetoitem_btn.setText("Add to Item");
        codetoitem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codetoitem_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/images/1ss.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(688, 688, 688)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1))
        );

        rtarrow_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        rtarrow_btn.setText("Add RightArrow");
        rtarrow_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtarrow_btnActionPerformed(evt);
            }
        });

        writetex_btn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        writetex_btn.setText("Write .tex");
        writetex_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writetex_btnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/images/arrow.png"))); // NOI18N

        arrow_check.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        arrow_check.setText("Add in Item");

        path_check.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        path_check.setText("Add in Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(23, 23, 23)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(path_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(12, 12, 12))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(para_label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(path_box, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(addSubSection_btn)
                                                .addComponent(addSec_btn)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(title_box, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(path_check)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(path_spaces)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addPath_btn)
                                                .addGap(4, 4, 4)))
                                        .addComponent(rtarrow_btn)
                                        .addComponent(arrow_check))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(item_check)
                                                .addGap(90, 90, 90)
                                                .addComponent(addrow_btn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(delrow_btn))
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(addItems_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(codebox_label, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane3))))
                            .addComponent(writetex_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(codetoitem_btn)
                                .addGap(18, 18, 18)
                                .addComponent(addCode_btn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(title_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(title_label)
                                .addComponent(item_check))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addrow_btn)
                                .addComponent(delrow_btn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(para_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSec_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSubSection_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(path_box, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(path_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(path_check)
                                    .addComponent(path_spaces, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPath_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(arrow_check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rtarrow_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codebox_label))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addItems_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codetoitem_btn)
                            .addComponent(addCode_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writetex_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codetoitem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codetoitem_btnActionPerformed
        DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
        int n = item_table.getSelectedRow();
        String p = this.code_box.getText();

        k = b.replaceAll("ccodec", p);
        k = k.replaceFirst("null", "");
        String s = (String) dft.getValueAt(n, 0);
        s = s + "\n " + k;
        s = s.replaceFirst("null", "");
        dft.setValueAt(s, n, 0);
        this.code_box.setText("//*Write your code here*");
    }//GEN-LAST:event_codetoitem_btnActionPerformed

    private void addItems_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItems_btnActionPerformed

        if (item_check.isSelected() == false) {
            if (this.item_table.isEditing()) {
                item_table.getCellEditor().stopCellEditing();
            }
            DefaultTableModel dft = (DefaultTableModel) item_table.getModel();

            dft.fireTableDataChanged();
            int row = dft.getRowCount();
            dft.fireTableRowsUpdated(0, row);
            dft.fireTableCellUpdated(row, 0);

            ArrayList<String> list = new ArrayList();
            int v = 0;

            while (v < row) {
                String x = (String) dft.getValueAt(v, 0);
                System.out.println("x: " + x);
                if (x == null) {
                    v++;
                } else {
                    list.add(x);
                    v++;
                }
            }

            for (int i = 0; i < list.size(); i++) {
                list.set(i, "\\item " + list.get(i));

            }
            String x = null;
            for (int i = 0; i < list.size(); i++) {
                x = x + "\n" + list.get(i);
            }
            x = x.replaceFirst("null", "");

            doc = doc + "\n" + x;

            updatePreview();

        } else if (item_check.isSelected() == true) {
            if (this.item_table.isEditing()) {
                item_table.getCellEditor().stopCellEditing();
            }
            DefaultTableModel dft = (DefaultTableModel) item_table.getModel();

            dft.fireTableDataChanged();
            int row = dft.getRowCount();
            dft.fireTableRowsUpdated(0, row);
            dft.fireTableCellUpdated(row, 0);
            ArrayList<String> list = new ArrayList();
            int v = 0;

            while (v < row) {
                String x = (String) dft.getValueAt(v, 0);

                if (x == null) {
                    v++;
                } else {
                    list.add(x);
                    v++;
                }
            }

            for (int i = 0; i < list.size(); i++) {
                list.set(i, "\\item " + list.get(i));

            }
            String x = null;

            for (int i = 0; i < list.size(); i++) {
                x = x + "\n " + list.get(i);
            }
            x = x.replaceFirst("null", "");

            x = "\\begin{enumerate}\n" + x + "\n\n \\end{enumerate}";

            doc = doc + "\n" + x;

            updatePreview();

        }
    }//GEN-LAST:event_addItems_btnActionPerformed

    private void delrow_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delrow_btnActionPerformed
        DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
        int n = this.item_table.getSelectedRow();
        dft.removeRow(n);
    }//GEN-LAST:event_delrow_btnActionPerformed

    private void addrow_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrow_btnActionPerformed

        DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
        dft.addRow(new String[]{});
    }//GEN-LAST:event_addrow_btnActionPerformed

    private void path_spacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_spacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_path_spacesActionPerformed

    private void addPath_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPath_btnActionPerformed
        if (path_check.isSelected() == false) {

            if (path_spaces.isSelected() == true) {
                String p = this.path_box.getText();
                k = p.replace("\\", "\\\\");
                k = a.replaceAll("cpathc", k);
                k = k.replaceFirst("null", "");

                System.out.println("h: " + k);

                doc = doc + "\n" + k + "\n";
                updatePreview();
                this.path_box.setText("");
            } else if (path_spaces.isSelected() == false) {
                String p = this.path_box.getText();
                //p = p.replace("\\", "\\\\");
                //p = "\\path{" + p + "}";
                //k = p.replace("\\", "\\\\");
                p = p.replaceFirst("null", "");

                String h = para_box.getText() + " \\path{" + p + "}";

                System.out.println("h: " + h);
                para_box.setText(h);
                updatePreview();
                this.path_box.setText("");
            }
        } else if (path_check.isSelected() == true) {
            if (path_spaces.isSelected() == true) {
                String p = this.path_box.getText();
                k = p.replace("\\", "\\\\");
                k = a.replaceAll("cpathc", k);
                k = k.replaceFirst("null", "");

                DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
                int n = item_table.getSelectedRow();

                String s = (String) dft.getValueAt(n, 0);
                s = s + "\n " + k;
                s = s.replaceFirst("null", "");
                dft.setValueAt(s, n, 0);

                path_box.setText("");
            } else if (path_spaces.isSelected() == false) {
                String p = this.path_box.getText();
                //p = p.replace("\\", "\\\\");
                //p = "\\path{" + p + "}";
                //k = p.replace("\\", "\\\\");
                p = p.replaceFirst("null", "");

                DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
                int n = item_table.getSelectedRow();

                String s = (String) dft.getValueAt(n, 0);
                s = s + " " + " \\path{" + p + "}";
                s = s.replaceFirst("null", "");
                dft.setValueAt(s, n, 0);

                path_box.setText("");
            }

        }
    }//GEN-LAST:event_addPath_btnActionPerformed

    private void item_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_checkActionPerformed

    private void addCode_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCode_btnActionPerformed
        String p = this.code_box.getText();

        k = b.replaceAll("ccodec", p);
        k = k.replaceFirst("null", "");

        doc = doc + "\n" + k;
        this.code_box.setText("//*Write your code here*");
        updatePreview();
    }//GEN-LAST:event_addCode_btnActionPerformed

    private void addSubSection_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubSection_btnActionPerformed
        String t = this.title_box.getText();
        String p = this.para_box.getText();

        k = j.replaceAll("ctitlec", t);
        k = k.replaceAll("cdescc", p);
        k = k.replaceFirst("null", "");
        k = k.replaceAll("(?m)^[ \t]*\r?\n", "");
        System.out.println(k);
        doc = doc + "\n" + k;
        this.para_box.setText("");
        this.title_box.setText("");

        updatePreview();
    }//GEN-LAST:event_addSubSection_btnActionPerformed

    private void addSec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSec_btnActionPerformed
        String t = this.title_box.getText();
        String p = this.para_box.getText();
        System.out.println();
        if ((t.equals("null") && p.equals("null")) || (t.equals("") && p.equals(""))) {
            updatePreview();
        } else if (t.equals("null") || t.equals("")) {
            String x = this.para_box.getText();
            doc = doc + "\n" + x;
            this.para_box.setText("");
            updatePreview();
        } else {
            k = l.replaceAll("ctitlec", t);
            System.out.println("p  : " + p);
            k = k.replace("cdescc", p);
            k = k.replaceFirst("null", "");
            //k = k.replaceAll("(?m)^[ \t]*\r?\n", "");
            doc = doc + "\n" + k;
            this.para_box.setText("");
            this.title_box.setText("");
            updatePreview();
        }
    }//GEN-LAST:event_addSec_btnActionPerformed

    private void title_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_boxActionPerformed

    private void rtarrow_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtarrow_btnActionPerformed
        if (arrow_check.isSelected() == false) {
            String p = "$\\Rightarrow$";
            String h = para_box.getText() + " " + p + " ";
            para_box.setText(h);

        } else if (arrow_check.isSelected() == true) {
            DefaultTableModel dft = (DefaultTableModel) item_table.getModel();
            int n = item_table.getSelectedRow();

            String p = "$\\Rightarrow$";
            String s = (String) dft.getValueAt(n, 0);
            s = s + "\n " + p;
            s = s.replaceFirst("null", "");
            dft.setValueAt(s, n, 0);

        }


    }//GEN-LAST:event_rtarrow_btnActionPerformed

    private void writetex_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writetex_btnActionPerformed
        doc = doc + "\n" + "\\end{document}";
        updatePreview();
        output_txt.write(doc);
        output_txt.close();
        output_tex.write(doc);
        output_tex.close();
    }//GEN-LAST:event_writetex_btnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCode_btn;
    private javax.swing.JButton addItems_btn;
    private javax.swing.JButton addPath_btn;
    private javax.swing.JButton addSec_btn;
    private javax.swing.JButton addSubSection_btn;
    private javax.swing.JButton addrow_btn;
    private javax.swing.JCheckBox arrow_check;
    private javax.swing.JTextArea code_box;
    private javax.swing.JLabel codebox_label;
    private javax.swing.JButton codetoitem_btn;
    private javax.swing.JButton delrow_btn;
    private javax.swing.JCheckBox item_check;
    private javax.swing.JTable item_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea para_box;
    private javax.swing.JLabel para_label;
    private javax.swing.JTextField path_box;
    private javax.swing.JCheckBox path_check;
    private javax.swing.JLabel path_label;
    private javax.swing.JCheckBox path_spaces;
    private javax.swing.JTextArea preview_box;
    private javax.swing.JButton rtarrow_btn;
    private javax.swing.JTextField title_box;
    private javax.swing.JLabel title_label;
    private javax.swing.JButton writetex_btn;
    // End of variables declaration//GEN-END:variables
}
